---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos
  template:
    src: repos_template.j2
    dest: /etc/yum.repos.d/3_tier_app_internal.repo

- name: yum clean
  shell: yum clean all
  
- name: install base tools and packages
  yum:
    name:
      - python-pip
    state: present
